language: ruby
rvm:
  - 2.4
script:
  - RAILS_ENV=test bundle exec rails db:migrate --trace
  - bundle exec rails db:test:prepare
  - bundle exec rails test
before_script:
  - psql -c 'create database strano_test' -U postgres
